"""
This type stub file was generated by pyright.
"""

from ._device import Attributes, Device, Devices, Tags

"""
    pyudev.device
    =============

    Device class implementation of :mod:`pyudev`.

    .. moduleauthor::  Sebastian Wiesner  <lunaryorn@gmail.com>
"""
