"""
This type stub file was generated by pyright.
"""

from . import libc, libudev

"""
    pyudev._ctypeslib
    =================

    Wrappers for libraries.

    .. moduleauthor::  mulhern  <amulhern@redhat.com>
"""
