"""
This type stub file was generated by pyright.
"""

"""
    pyudev._ctypeslib.libc
    ======================

    Wrappers for libc.

    .. moduleauthor::  Sebastian Wiesner  <lunaryorn@gmail.com>
"""
FD_PAIR = ...
SIGNATURES = ...
ERROR_CHECKERS = ...
