"""
This type stub file was generated by pyright.
"""

from pyudev._errors import DeviceNotFoundAtPathError, DeviceNotFoundByFileError, DeviceNotFoundByNameError, DeviceNotFoundByNumberError, DeviceNotFoundError, DeviceNotFoundInEnvironmentError
from pyudev._util import udev_version
from pyudev.core import Context, Enumerator
from pyudev.device import Attributes, Device, Devices, Tags
from pyudev.discover import DeviceFileHypothesis, DeviceNameHypothesis, DeviceNumberHypothesis, DevicePathHypothesis, Discovery
from pyudev.monitor import Monitor, MonitorObserver
from pyudev.version import __version__, __version_info__

"""
    pyudev
    ======

    A binding to libudev.

    The :class:`Context` provides the connection to the udev device database
    and enumerates devices.  Individual devices are represented by the
    :class:`Device` class.

    Device monitoring is provided by :class:`Monitor` and
    :class:`MonitorObserver`.  With :mod:`pyudev.pyqt4`, :mod:`pyudev.pyside`,
    :mod:`pyudev.glib` and :mod:`pyudev.wx` device monitoring can be integrated
    into the event loop of various GUI toolkits.

    .. moduleauthor::  Sebastian Wiesner  <lunaryorn@gmail.com>
"""
