"""
This type stub file was generated by pyright.
"""

"""
    pyudev.pyside
    =============

    PySide integration.

    :class:`QUDevMonitorObserver` integrates device monitoring into the
    PySide\\_ mainloop by turing device events into Qt signals.

    :mod:`PySide.QtCore` from PySide\\_ must be available when importing this
    module.

    .. _PySide: http://www.pyside.org

    .. moduleauthor::  Sebastian Wiesner  <lunaryorn@gmail.com>
    .. versionadded:: 0.6
"""
MonitorObserver = ...
