"""
This type stub file was generated by pyright.
"""

"""
    pyudev.version
    ==============

    Version information.

    .. moduleauthor::  mulhern  <amulhern@redhat.com>
"""
__version_info__ = ...
__version__ = ...
